from typing import Self

import joblib
import pandas as pd
from sklearn.exceptions import NotFittedError
from sklearn.neural_network import MLPRegressor
from sklearn.preprocessing import PolynomialFeatures, StandardScaler

from model_types import ActivationType, ModelState


class NeuralNetwork:
    """
    NeuralNetwork provides an encapsulated wrapper around sklearn's MLPRegressor.

    Operational Requirements:
    1. Features must be passed as pandas DataFrames to maintain consistency in
       feature names and prevent StandardScaler warnings.
    2. Model persistence is handled via a state dictionary containing both
       the fitted scaler and the model weights.

    Implementation Note:
    Unlike raw MLPRegressor, this class manages its own internal state for
    StandardScaler. This ensures that when a model is loaded for inference,
    it applies the exact same mean/variance scaling used during the
    original training session.
    """

    def __init__(
        self,
        hidden_layers: tuple[int, ...] = (5,),
        activation: ActivationType = "relu",
        max_iter=10000,
        alpha=0.0001,
        device: str | None = None,
        use_polynomial: bool = True,
    ) -> None:
        """
        Initializes the model with specific architecture and regularization.

        Args:
            hidden_layers: Topology of the network (e.g., (8, 4) for two layers).
            activation: Activation function ('logistic', 'tanh', 'relu').
            alpha: L2 penalty (regularization term) to prevent overfitting in
                   noisy experimental data.
        """
        self.scaler = StandardScaler()
        self.use_polynomial = use_polynomial
        self.poly = (
            PolynomialFeatures(degree=2, include_bias=False) if use_polynomial else None
        )
        self.model = MLPRegressor(
            hidden_layer_sizes=hidden_layers,
            activation=activation,
            solver="lbfgs",
            alpha=alpha,
            max_iter=max_iter,
            random_state=42,
        )

    def fit(self, X_train: pd.DataFrame, y_train: pd.Series) -> None:
        """
        Trains the internal model using the provided machining parameters.

        Note:
        Automatically executes fit_transform on the internal scaler. If data
        contains NaNs or non-numeric types, a ValueError is raised.
        """

        try:
            self.feature_names = X_train.columns.tolist()
            X_processed = (
                self.poly.fit_transform(X_train)
                if self.use_polynomial
                else X_train.values
            )
            X_train_scaled = self.scaler.fit_transform(X_processed)
            self.model.fit(X_train_scaled, y_train)
        except ValueError as e:
            raise ValueError(
                f"Training failed due to invalid data format: {e}"
            ) from None

    def predict(self, x_test: pd.DataFrame):
        """
        Predicts surface roughness for a given set of machining inputs.

        Operational Requirement:
        The input DataFrame must contain the same columns (in the same order)
        as the training set.

        Returns:
            The predicted Ra value as a float.
        """
        try:
            x_processed = (
                self.poly.transform(x_test) if self.use_polynomial else x_test.values
            )
            x_test_scaled = self.scaler.transform(x_processed)
            predictions = self.model.predict(x_test_scaled)

            return float(predictions[0])
        except NotFittedError:
            raise NotFittedError(
                "The model must be trained or loaded before making predictions."
            ) from None
        except ValueError as e:
            raise ValueError(
                f"Prediction failed due to mismatched input features: {e}"
            ) from None

    def save(self, filepath: str) -> None:
        """Saves both the model and the scaler into a single file."""
        try:
            state: ModelState = {
                "model": self.model,
                "scaler": self.scaler,
                "features": getattr(self, "feature_names", []),
                "poly": getattr(self, "poly", None),
                "use_polynomial": getattr(self, "use_polynomial", False),
            }
            joblib.dump(state, filepath)

            print(f"Network successfully saved to {filepath}")
        except OSError as e:
            raise OSError(
                f"Could not save the model to '{filepath}'. Check directory permissions: {e}"
            ) from None

    @classmethod
    def load(cls, filepath: str) -> Self:
        """
        Reconstructs a NeuralNetwork instance from a binary state file.

        Deployment Note:
        Requires a valid .pkl file generated by the .save() method. The file
        must contain the 'model' and 'scaler' keys or a KeyError will be raised.
        """
        try:
            state: ModelState = joblib.load(filepath)

            if "model" not in state or "scaler" not in state or "features" not in state:
                raise KeyError(
                    "The loaded file is missing the 'model' or 'scaler' state."
                )

            network = cls()

            network.model = state["model"]
            network.scaler = state["scaler"]
            network.feature_names = state.get("features", [])
            network.poly = state.get("poly", None)
            network.use_polynomial = state.get("use_polynomial", False)

            return network

        except FileNotFoundError:
            raise FileNotFoundError(
                f"Error: The model file '{filepath}' does not exist."
            ) from None
        except KeyError as e:
            raise KeyError(
                f"Error: The file is corrupted or not a valid NeuralNetwork state: {e}"
            ) from None
        except Exception as e:
            raise RuntimeError(
                f"An unexpected error occurred while loading the model: {e}"
            ) from None
