from typing import Self

import joblib
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from mealpy import NGO, FloatVar
from sklearn.exceptions import NotFittedError
from sklearn.preprocessing import PolynomialFeatures, StandardScaler

from model_types import ActivationType, ModelState


class PyTorchMLP(nn.Module):
    """
    A PyTorch-based Multi-Layer Perceptron to replace sklearn's MLPRegressor.
    This allows us to expose the network's weights so the NGO algorithm can train them.
    """

    def __init__(
        self,
        num_inputs: int,
        hidden_layers: tuple[int, ...],
        activation: ActivationType,
    ):
        super().__init__()
        layers = []
        in_features = num_inputs

        for hidden_dim in hidden_layers:
            layers.append(nn.Linear(in_features, hidden_dim))
            if activation == "relu":
                layers.append(nn.ReLU())
            elif activation == "tanh":
                layers.append(nn.Tanh())
            elif activation == "logistic":
                layers.append(nn.Sigmoid())
            in_features = hidden_dim

        layers.append(nn.Linear(in_features, 1))
        self.network = nn.Sequential(*layers)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.network(x).squeeze()

    def set_weights(self, flat_weights: np.ndarray, device: torch.device):
        """
        Injects a flat array of weights (generated by NGO) back into the PyTorch layers.
        """
        ptr = 0
        for param in self.parameters():
            num_param = param.numel()
            param_slice = flat_weights[ptr : ptr + num_param]
            param.data.copy_(
                torch.tensor(param_slice, dtype=torch.float32, device=device).reshape(
                    param.shape
                )
            )
            ptr += num_param


class NeuralNetworkNGO:
    """
    NeuralNetwork provides an encapsulated wrapper around a PyTorch MLP,
    trained using a Hybrid approach: Northern Goshawk Optimization (NGO) for global
    search, followed by L-BFGS for exact local fine-tuning.
    """

    def __init__(
        self,
        hidden_layers: tuple[int, ...] = (5,),
        activation: ActivationType = "relu",
        max_iter: int = 100,
        alpha: float = 0.0001,
        device: str | None = None,
        use_polynomial: bool = False,
    ) -> None:

        self.scaler = StandardScaler()
        self.use_polynomial = use_polynomial
        self.poly = (
            PolynomialFeatures(degree=2, include_bias=False) if use_polynomial else None
        )

        self.hidden_layers = hidden_layers
        self.activation = activation
        self.epochs = max_iter
        self.pop_size = 30
        self.alpha = alpha
        self.model = None

        if device == "gpu" and torch.cuda.is_available():
            self.device = torch.device("cuda")
        else:
            self.device = torch.device("cpu")

    def fit(self, X_train: pd.DataFrame, y_train: pd.Series) -> Self:
        try:
            torch.manual_seed(42)
            if self.device.type == "cuda":
                torch.cuda.manual_seed_all(42)

            self.feature_names = X_train.columns.tolist()

            X_processed = (
                self.poly.fit_transform(X_train)
                if self.use_polynomial
                else X_train.values
            )

            X_train_scaled = self.scaler.fit_transform(X_processed)

            X_tensor = torch.tensor(
                X_train_scaled, dtype=torch.float32, device=self.device
            )
            y_tensor = torch.tensor(
                y_train.values, dtype=torch.float32, device=self.device
            )

            num_inputs = X_tensor.shape[1]

            self.model = PyTorchMLP(
                num_inputs=num_inputs,
                hidden_layers=self.hidden_layers,
                activation=self.activation,
            ).to(self.device)

            total_params = sum(p.numel() for p in self.model.parameters())

            def training_objective(weights_vector):
                with torch.no_grad():
                    self.model.set_weights(weights_vector, self.device)
                    predictions = self.model(X_tensor)

                    # MSE Loss
                    criterion = nn.MSELoss()
                    loss = criterion(predictions, y_tensor)

                    # L2 Regularization
                    l2_reg = sum(torch.norm(p, p=2) for p in self.model.parameters())
                    total_loss = loss + (self.alpha * l2_reg)

                return total_loss.item()

            problem_dict = {
                "bounds": FloatVar(
                    lb=[-5.0] * total_params,
                    ub=[5.0] * total_params,
                    name="ann_weights",
                ),
                "obj_func": training_objective,
                "minmax": "min",
            }

            ngo_solver = NGO.OriginalNGO(epoch=self.epochs, pop_size=self.pop_size)
            best_agent = ngo_solver.solve(problem_dict)

            with torch.no_grad():
                self.model.set_weights(best_agent.solution, self.device)

            optimizer = torch.optim.LBFGS(
                self.model.parameters(),
                lr=0.1,
                max_iter=500,
                line_search_fn="strong_wolfe",
            )

            def closure():
                optimizer.zero_grad()
                predictions = self.model(X_tensor)
                criterion = nn.MSELoss()
                loss = criterion(predictions, y_tensor)
                l2_reg = sum(torch.norm(p, p=2) for p in self.model.parameters())
                total_loss = loss + (self.alpha * l2_reg)
                total_loss.backward()
                return total_loss

            optimizer.step(closure)

            return self

        except ValueError as e:
            raise ValueError(
                f"Training failed due to invalid data format: {e}"
            ) from None

    def predict(self, x_test: pd.DataFrame) -> float:
        if self.model is None:
            raise NotFittedError(
                "The model must be trained or loaded before making predictions."
            )

        try:
            x_processed = (
                self.poly.transform(x_test) if self.use_polynomial else x_test.values
            )
            x_test_scaled = self.scaler.transform(x_processed)
            x_tensor = torch.tensor(
                x_test_scaled, dtype=torch.float32, device=self.device
            )

            self.model.eval()
            with torch.no_grad():
                predictions = self.model(x_tensor)

            if predictions.dim() == 0:
                return float(predictions.cpu().item())
            return float(predictions[0].cpu().item())

        except ValueError as e:
            raise ValueError(
                f"Prediction failed due to mismatched input features: {e}"
            ) from None

    def save(self, filepath: str) -> None:
        if self.model is None:
            raise NotFittedError("Cannot save an untrained model.")

        try:
            state: ModelState = {
                "model": self.model,
                "scaler": self.scaler,
                "features": getattr(self, "feature_names", []),
                "poly": getattr(self, "poly", None),
                "use_polynomial": getattr(self, "use_polynomial", False),
            }
            joblib.dump(state, filepath)
            print(f"Network successfully saved to {filepath}")
        except OSError as e:
            raise OSError(f"Could not save the model to '{filepath}': {e}") from None

    @classmethod
    def load(cls, filepath: str, device: str | None = None) -> Self:
        try:
            state: ModelState = joblib.load(filepath)

            if "model" not in state or "scaler" not in state or "features" not in state:
                raise KeyError(
                    "The loaded file is missing the 'model' or 'scaler' state."
                )

            network = cls(device=device)
            network.model = state["model"].to(network.device)
            network.scaler = state["scaler"]
            network.feature_names = state.get("features", [])
            network.poly = state.get("poly", None)
            network.use_polynomial = state.get("use_polynomial", False)

            network.model.eval()
            return network

        except FileNotFoundError:
            raise FileNotFoundError(
                f"Error: The model file '{filepath}' does not exist."
            ) from None
        except Exception as e:
            raise RuntimeError(
                f"An unexpected error occurred while loading the model: {e}"
            ) from None
